KlubJagiellonski/pola-backend

- .gitignore
- Development_with_Docker.md
- Dockerfile
- Makefile
- utils/docker_run.sh
- utils/dump_db_from_heroku.sh
- utils/restore_db_from_dump.sh
> support for development with Docker

- product/filters.py
Reverts KlubJagiellonski/pola-backend#24
> Revert "Update filters.py"

- pola/templates/partiales/friends.html
> Klub Przyjaciół Poli 2

- pola/templates/partiales/friends.html
> Italian Fashion

- pola/rpc_api/views.py
Co-authored-by: Kamil Breguła <mik-laj@users.noreply.github.com>
> Dodaje nagłowki CORS (#271)

- .github/workflows/ci.yml
Hej.
My kasujemy ostatnio trochę endpointów, co może spowodowąć, żę będziemy mieli nieużywany kod, gdy skasujemy zbyt mało. Aby to wykryć dodaje codecov
Pozdrwiam
> Upload coverage to codecov

- report/templates/report/report_detail.html
- report/templates/report/report_resolve_all.html
- report/tests.py
- report/urls.py
- report/views.py
https://github.com/KlubJagiellonski/pola-backend/issues/368
> add "resolve all reports with the same product" button

- scripts/prod-docker-image/Dockerfile
Cześć.
Nowa wersja dodała nowe reguły, które sprawdzają, czy instrukcje RUN są prawidłowo skonsolidowane. Niestety ta reguła nie jest kompletna, bo nie bierze pod uwagę jeszcze ARG i ENV (bilet: https://github.com/hadolint/hadolint/issues/557), ale to tez uwzgledniłem w tej zmianie.
Z wyrazami szacunku
> Fix hadolint errors and optimise image a bit more

- pola/logic.py
- pola/tests/test_logic.py
https://github.com/KlubJagiellonski/pola-backend/issues/560
> Brands - compatibility API V3 with API V4

- pola/logic.py
- pola/rpc_api/tests/test_views.py
- pola/rpc_api/views.py
https://github.com/KlubJagiellonski/pola-backend/issues/558
> Fill name field for API v4

- .pre-commit-config.yaml
- pola/management/commands/import_brands.py
- pola/tests/commands/test_import_brands.py
- pola/tests/commands/test_import_brands_fixture.tsv
https://github.com/KlubJagiellonski/pola-backend/issues/497
> Add brand import script

- pola/templates/partiales/friends.html
Duża prośba o pilną akceptację. Potrzebuję screen do sprawozdania.
> Poprawki opisu

- pola/rpc_api/api_models.py
- pola/rpc_api/tests/test_views_v4.py
Close: https://github.com/KlubJagiellonski/pola-backend/issues/1316
> Display company common names in search endpoint

- pola/templates/partiales/friends.html
> Usunięcie Piwojada z web view w aplikacji

- pola/constants.py
- pola/rpc_api/tests/test_views_v4.py
> Mat perowicz patch 2024

- pola/constants.py
- pola/rpc_api/tests/test_views_v4.py
> Akcja 1,5% podatku

- pola/company/templates/company/company_detail.html
- pola/company/tests/test_views.py
- pola/company/views.py
- pola/templatetags/pola_extras.py
- pola/tests/test_templatetags.py
Tak to teraz wygląda:
Close: https://github.com/KlubJagiellonski/pola-backend/issues/3732
> Dodaj kartę producenta do CMS

- .github/workflows/ci.yml
- .github/workflows/migration_check.yml
- .github/workflows/update_constraints.yml
- docs/start.rst
- docs/testing.rst
- run_dbt.sh
- run_manage.sh
- run_test.sh
- scripts/pull_images.py
> Fix failing CI builds

- scripts/prod-docker-image/Dockerfile
- scripts/prod-docker-image/_functions.sh
- Zmiana pythona na 3.11
- Zmiana bas image na debian bookworm
- wagoodman/dive nie jest rozwijane. Zmianana na fork joschi/dive
- Refaktoring Dockerfile
> Update python3.11, nie korzystamy z openshift

- codecov.yml
Jak w komentarzu: https://github.com/KlubJagiellonski/pola-backend/pull/4433#issuecomment-2954114338
PR musi być zmergowany przed   #4431  #4433 #4432 :cat:
> Dodanie codecov.yml

- pola/company/filters.py
- pola/templates/pages/home-cms.html
Pominięte rzeczy z PR 
https://github.com/KlubJagiellonski/pola-backend/pull/4677
Analogiczna zmiana.
> Dodatkowa zmiana url do filtrowania najpopularniejszych produktów na głównej stronie CMS
